name: CI

on:
  schedule:
    - cron:  '0 0 * * 1'
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build archlinux package
        uses: countstarlight/arch-makepkg-action@master
        with:
          #repos: >
          #  archlinuxcn=https://geo-mirror.chaotic.cx/$repo/$arch
          #before: "sudo pacman -S --noconfirm archlinux-keyring chaotic-keyring chaotic-mirrorlist"
          # packages: >
          #   aria2
          #   qt5-tools
          #   xterm
          #   xorg-fonts-100dpi
          #   xorg-fonts-75dpi
          #   xorg-fonts-cyrillic
          #   xorg-fonts-type1
          #   xorg-fonts-misc
          #   cabextract
          #   perl
          #   unzip
          #   xorg-xmessage
          #   zenity
          #   yad
          #   xkb-switch
          #   imagemagick
          #   icoutils
          #   lib32-mangohud
          #   lib32-vkbasalt
          #   mangohud
          #   mangohud-common
          #   vkbasalt
          #   gamemode
          #   lib32-gamemode
          #   giflib
          #   lib32-giflib
          #   libpng
          #   lib32-libpng
          #   libldap
          #   lib32-libldap
          #   gnutls
          #   lib32-gnutls
          #   mpg123
          #   lib32-mpg123
          #   openal
          #   lib32-openal
          #   v4l-utils
          #   lib32-v4l-utils
          #   libpulse
          #   lib32-libpulse
          #   libgpg-error
          #   lib32-libgpg-error
          #   alsa-plugins
          #   lib32-alsa-plugins
          #   alsa-lib
          #   lib32-alsa-lib
          #   libjpeg-turbo
          #   lib32-libjpeg-turbo
          #   sqlite
          #   lib32-sqlite
          #   libxcomposite
          #   lib32-libxcomposite
          #   libxinerama
          #   lib32-libgcrypt
          #   libgcrypt
          #   lib32-libxinerama
          #   ncurses
          #   lib32-ncurses
          #   opencl-icd-loader
          #   lib32-opencl-icd-loader
          #   libxslt
          #   lib32-libxslt
          #   libva
          #   lib32-libva
          #   gtk3
          #   lib32-gtk3
          #   lib32-vulkan-icd-loader
          #   vulkan-headers
          #   vulkan-icd-loader
          #   vulkan-tools
          #   mesa
          #   lib32-glu
          #   glu
          #   lib32-libva-mesa-driver
          #   lib32-mesa
          #   libva-mesa-driver
          #   mesa-demos
          #   mesa-utils
          #   mesa-vdpau
          #   vulkan-mesa-layers
          #   lib32-vulkan-mesa-layers
          #   libstrangle-git
          #   openssl
          #   libnotify
          #   coreutils
          #   libxrandr
          #   lib32-libxrandr
          #   xorg-xrandr
          #   bc
          #   xorg-xgamma
          #   lsb-release
          #   iputils
          #   curl
          #   xdelta3
          #   latencyflex-git
          #   latencyflex-wine-git
          #   xdg-utils
          #   desktop-file-utils
          #   squashfs-tools
          #   squashfuse
          #   fuse2
          #   reshade-shaders-git
          #   winetricks
          #   innoextract
          #   p7zip
          #   gnu-netcat
          scripts: "makepkg --nodeps"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: lutris-wine-git-*.pkg*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
